### ISSUE TITLE
extractSigsIndel:  paste fails due to very long string

### ISSUE THREAD

**Issue by ThomasGro** [UMCUGenetics/mutSigExtractor#3]
My command was:
extractSigsIndel(file5.vcf, vcf.filter='PASS', verbose = T, keep.chroms=paste0('chr',c(1:22,"X","Y")))

Loading variants...
Reading in vcf file...
 Show Traceback
 
Error in paste(clean_lines, collapse = "\n") : 
  result would exceed 2^31-1 bytes 

> traceback()
11: paste(clean_lines, collapse = "\n")
10: textConnection(text, encoding = "UTF-8")
9: read.table(file = file, header = header, sep = sep, quote = quote, 
       dec = dec, fill = fill, comment.char = comment.char, ...)
8: read.delim(text = paste(clean_lines, collapse = "\n"), check.names = F, 
       stringsAsFactors = F)
7: readVcfFields(vcf.file, vcf_fields)
6: variantsFromVcf(vcf.file, mode = "snv_indel", ref.genome = ref.genome, 
       verbose = verbose, ...)
5: extractSigsIndel(x, vcf.filter = "PASS", verbose = T, keep.chroms = paste0("chr", 
       c(1:22, "X", "Y"))) at #2
4: FUN(X[[i]], ...)
3: lapply(X = X, FUN = FUN, ...)
2: sapply(snv_paths, FUN = function(x) {
       extractSigsIndel(x, vcf.filter = "PASS", verbose = T, keep.chroms = paste0("chr", 
           c(1:22, "X", "Y")))
       gc()
   })
1: sapply(snv_paths, FUN = function(x) {
       extractSigsIndel(x, vcf.filter = "PASS", verbose = T, keep.chroms = paste0("chr", 
           c(1:22, "X", "Y")))
       gc()
   })

**Comment by luannnguyen** [comment]
I've just added a fix for this. Vcf should now be read regardless of the size.

**Comment by ThomasGro** [comment]
Thank you Luan.
I notices an bug in the new version:

>Error in getContextsIndel(df, ref.genome = ref.genome, verbose = verbose,  : 
                            object 'vcf' not found 

In the getContextsIndel function you have:
>vcf <- vcf[!grepl(',',vcf$alt),]

where I belief it should be 

 >df <- df[!grepl(',',df$alt),]

**Comment by luannnguyen** [comment]
Thanks for catching this! I've merged the fix to v1.09
