### ISSUE TITLE
extractSigsIndel error

### ISSUE THREAD

**Issue by alhafidzhamdan** [UMCUGenetics/mutSigExtractor#4]
Hi there,

I'm just trying your package today and it worked really well for most things apart from this error for indel sig calling for PCAWG. It worked for CHORD but not PCAWG.

My command is:
```
indel_context <- extractSigsIndel(
  vcf.file = vcf_snv,
  vcf.filter='PASS',
  method = "pcawg",
  output='signatures',
  signature.profiles=INDEL_SIGNATURE_PROFILES,
  ref.genome=BSgenome.Hsapiens.UCSC.hg38
)

```

Error:
```
Error in .Call2("solve_user_SEW", refwidths, start, end, width, translate.negative.coord,  : 
  solving row 667: 'allow.nonnarrowing' is FALSE and the supplied start (78568346) is > refwidth + 1


```

Could you please help me troubleshoot?

Thanks!

Al

**Comment by luannnguyen** [comment]
Hi Al,

This error is from getSeq() from the Biostrings package.
Seems like it's trying to retrieve a genome location that's out of bounds.

Is it possible that the vcf you're using is from hg19 (whereas here you're querying hg38)?
Alternatively maybe you can also try filtering the vcf for 'normal' chromosomes using the keep.chroms argument:
`extractSigsIndel(..., keep.chroms=c(1:22,'X'))`

Luan

**Comment by alhafidzhamdan** [comment]
Hi there,

Thanks for getting back.
My VCFs are from hg38 for sure. 

` extractSigsIndel(..., keep.chroms=c(1:22,'X'))`still throws the same error.
I have also excluded non-canonical chrs manually and still the same error.

Funny enough that extractSigsSnv and other extractSig functions worked really well.

**Comment by luannnguyen** [comment]
Hi,

I changed extractSigsIndel() so that it uses BSgenome::getSeq() instead of Biostrings::getSeq().
It could be that the other extractSigs functions work because they use BSgenome::getSeq().
Could you test again if this works for you? Otherwise, could you to send me one of vcfs? Would make it easier for me to debug.

Luan

**Comment by alhafidzhamdan** [comment]
Hi Luan,

I used `devtools::install_github('https://github.com/UMCUGenetics/mutSigExtractor/')`
to reinstall the package. Still the same error.
I've used another VCF sample and still the same error.
I suspect it's to do with with pcawg-specific function?
I can send you a VCF to your email?
Thanks for looking into this.
A

**Comment by luannnguyen** [comment]
Hi Al,

No problem. You can email me at n.l.nguyen-2@umcutrecht.nl

Luan

**Comment by alhafidzhamdan** [comment]
Cheers- sent.

**Comment by luannnguyen** [comment]
Found the problem. The hg38 genome wasn't being passed to getSeq() and it was using the default genome (hg19).
I've now fixed the issue. Could you check again if it now works for you?

**Comment by alhafidzhamdan** [comment]
Fantastic! it works now! Thanks for looking into this. i'm amazed by how this is much more efficient in assigning signatures than most packages out there! Good job!

**Comment by luannnguyen** [comment]
You're welcome!
And thanks! Glad the optimizations i did didn't go unnoticed :)
