### ISSUE TITLE
unable to find an inherited method for function ‘seqinfo’ for signature ‘"NULL"'

### ISSUE THREAD

**Issue by pdiakumis** [UMCUGenetics/mutSigExtractor#6]
Hi @luannnguyen, 
I'm using CHORD and I think the fact `ref.genome` isn't getting passed into `subsetSmnvs` here https://github.com/UMCUGenetics/mutSigExtractor/blob/c615c6a0d622d3e82a56cc38cfe92884b877f210/R/extractSigsSnv.R#L42 causes this line https://github.com/UMCUGenetics/mutSigExtractor/blob/c615c6a0d622d3e82a56cc38cfe92884b877f210/R/subsetSmnvs.R#L76 to try and run `GenomeInfoDb::seqlevelsStyle(NULL)`, which gives you:

```
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'seqlevelsStyle': unable to find an inherited method for function ‘seqinfo’ for signature ‘"NULL"’
```

**Comment by pdiakumis** [comment]
Issue https://github.com/UMCUGenetics/mutSigExtractor/issues/5 might be related to this too.

**Comment by luannnguyen** [comment]
@pdiakumis Thanks for catching this! I've now added `ref.genome=ref.genome` to `subsetSmnvs()` within all of the extractSigs* functions. Hopefully this solves the issue

**Comment by pdiakumis** [comment]
Awesome, works now - thanks so much for sorting this out so quickly!
