### ISSUE TITLE
NNLM package

### ISSUE THREAD

**Issue by umasstr** [UMCUGenetics/mutSigExtractor#8]
There is an error that terminates extractSigsSnv referring to a package "NNLM." I'm not sure if the above warning is related.

![image](https://user-images.githubusercontent.com/44478133/196073058-1d0ece87-7589-48f7-91cd-f08d03d63396.png)

**Comment by luannnguyen** [comment]
Hi, i've fixed the if else statement that decides between the NNLM or R implementation of signature fitting. Could you check if it works now?

**Comment by umasstr** [comment]
I pulled the package again with devtools and got the same error. The install output is below. Does it look like it caught the version that you just pushed?

Thanks for the quick reply!


> devtools::install_github('https://github.com/UMCUGenetics/mutSigExtractor/')
Downloading GitHub repo UMCUGenetics/mutSigExtractor@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?
 1: All                                        
 2: CRAN packages only                         
 3: None                                       
 4: bitops       (1.0-6    -> 1.0-7    ) [CRAN]
 5: formatR      (1.8      -> 1.12     ) [CRAN]
 6: RCurl        (1.98-1.3 -> 1.98-1.9 ) [CRAN]
 7: crayon       (1.4.1    -> 1.5.2    ) [CRAN]
 8: BH           (1.75.0-0 -> 1.78.0-0 ) [CRAN]
 9: snow         (0.4-3    -> 0.4-4    ) [CRAN]
10: BiocGenerics (0.36.0   -> 0.36.1   ) [CRAN]
11: GenomeInfoDb (1.26.4   -> 1.26.7   ) [CRAN]
12: matrixStats  (0.58.0   -> 0.62.0   ) [CRAN]
13: DelayedArray (0.16.2   -> 0.16.3   ) [CRAN]
14: XML          (3.99-0.6 -> 3.99-0.11) [CRAN]
Enter one or more numbers, or an empty line to skip updates:3
✔  checking for file ‘/tmp/RtmpdStVaC/remotes192701efd34fb/UMCUGenetics-mutSigExtractor-1dfd05d/DESCRIPTION’ ...
─  preparing ‘mutSigExtractor’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘mutSigExtractor_1.27.tar.gz’
Installing package into '/home/tr52w/R/x86_64-pc-linux-gnu-library/4.0'
(as 'lib' is unspecified)
 installing *source* package ‘mutSigExtractor’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
NNLM package not installed. A (slow) R implementation will be used for fitting mutation contexts to signatures. 
The fast C++ implementation from NNLM is recommended when fitting context matrices with many samples.
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Warning in fun(libname, pkgname) :
   No reference genome loaded. Please install and load a BSgenome.
   For example:
      install.packages('BiocManager')
      BiocManager::install('BSgenome.Hsapiens.UCSC.hg19')
      library('BSgenome.Hsapiens.UCSC.hg19')
   Then specify the BSgenome to the ref.genome arguemnts to the relevant functions.
   For example:
      extractSigsSnv(..., ref.genome=BSgenome.Hsapiens.UCSC.hg19)
** testing if installed package can be loaded from final location
Warning in fun(libname, pkgname) :
   No reference genome loaded. Please install and load a BSgenome.
   For example:
      install.packages('BiocManager')
      BiocManager::install('BSgenome.Hsapiens.UCSC.hg19')
      library('BSgenome.Hsapiens.UCSC.hg19')
   Then specify the BSgenome to the ref.genome arguemnts to the relevant functions.
   For example:
      extractSigsSnv(..., ref.genome=BSgenome.Hsapiens.UCSC.hg19)
testing if installed package keeps a record of temporary installation path
DONE (mutSigExtractor)

**Comment by luannnguyen** [comment]
Just to confirm, you're still getting the "There is no 'NNLM' package" error? That's strange because the `extractSigsSnv()` function does work for me if i remove the NNLM package from my system.

What you could try is running `extractSigsSnv(path_to_vcf_file, output='contexts')`. This will bypass the signature fitting and i would like to see if the error is gone then.

What you can also try is install NNLM to make the error go away: `devtools::install_github('linxihui/NNLM')`

**Comment by umasstr** [comment]
Installing NNLM worked, thanks!
